/**
 * PlatformPublicAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EndedSubscription
 */
class EndedSubscription extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.membershipStarted = this.constructor.getValue(obj.membershipStarted);
        this.membershipTo = this.constructor.getValue(obj.membershipTo);
        this.active = this.constructor.getValue(obj.active);
        this.refunded = this.constructor.getValue(obj.refunded);
        this.isPastDue = this.constructor.getValue(obj.isPastDue);
        this.cancelled = this.constructor.getValue(obj.cancelled);
        this.membership = this.constructor.getValue(obj.membership);
        this.period = this.constructor.getValue(obj.period);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'membershipStarted', realName: 'membershipStarted' },
            { name: 'membershipTo', realName: 'membershipTo' },
            { name: 'active', realName: 'active' },
            { name: 'refunded', realName: 'refunded' },
            { name: 'isPastDue', realName: 'isPastDue' },
            { name: 'cancelled', realName: 'cancelled' },
            { name: 'membership', realName: 'membership', type: 'Membership' },
            { name: 'period', realName: 'period', type: 'Period' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EndedSubscription;
