/**
 * PlatformPublicAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ModulesAnalytic
 */
class ModulesAnalytic extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.progress = this.constructor.getValue(obj.progress);
        this.lessonsAnalytics = this.constructor.getValue(obj.lessonsAnalytics);
        this.id = this.constructor.getValue(obj.id || obj._id);
        this.name = this.constructor.getValue(obj.name);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'progress', realName: 'progress' },
            {
                name: 'lessonsAnalytics',
                realName: 'lessonsAnalytics',
                array: true,
                type: 'LessonsAnalytic',
            },
            { name: 'id', realName: '_id' },
            { name: 'name', realName: 'name' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ModulesAnalytic;
