/**
 * PlatformPublicAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Order
 */
class Order extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id || obj._id);
        this.vs = this.constructor.getValue(obj.vs);
        this.price = this.constructor.getValue(obj.price);
        this.createdAt = this.constructor.getValue(obj.createdAt);
        this.course = this.constructor.getValue(obj.course);
        this.checkout = this.constructor.getValue(obj.checkout);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: '_id' },
            { name: 'vs', realName: 'vs' },
            { name: 'price', realName: 'price' },
            { name: 'createdAt', realName: 'createdAt' },
            { name: 'course', realName: 'course', type: 'Course2' },
            { name: 'checkout', realName: 'checkout', type: 'Checkout' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Order;
