/**
 * PlatformPublicAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Reward
 */
class Reward extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.title = this.constructor.getValue(obj.title);
        this.minPoints = this.constructor.getValue(obj.minPoints);
        this.maxPoints = this.constructor.getValue(obj.maxPoints);
        this.creditsReward = this.constructor.getValue(obj.creditsReward);
        this.courses = this.constructor.getValue(obj.courses);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'title', realName: 'title' },
            { name: 'minPoints', realName: 'minPoints' },
            { name: 'maxPoints', realName: 'maxPoints' },
            { name: 'creditsReward', realName: 'creditsReward' },
            { name: 'courses', realName: 'courses', array: true, type: 'Course2' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Reward;
