/**
 * PlatformPublicAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const M200GetUsers = require('../lib/Models/M200GetUsers');
const Item = require('../lib/Models/Item');
const Course = require('../lib/Models/Course');
const Pagination = require('../lib/Models/Pagination');
const M200GetUser = require('../lib/Models/M200GetUser');
const FinishedLesson = require('../lib/Models/FinishedLesson');
const InProgressLesson = require('../lib/Models/InProgressLesson');
const PurchasedCourse = require('../lib/Models/PurchasedCourse');
const PurchasedLesson = require('../lib/Models/PurchasedLesson');
const Course1 = require('../lib/Models/Course1');
const ModulesAnalytic = require('../lib/Models/ModulesAnalytic');
const LessonsAnalytic = require('../lib/Models/LessonsAnalytic');
const Order = require('../lib/Models/Order');
const Course2 = require('../lib/Models/Course2');
const Checkout = require('../lib/Models/Checkout');
const Quize = require('../lib/Models/Quize');
const Result = require('../lib/Models/Result');
const Reward = require('../lib/Models/Reward');
const Subscription = require('../lib/Models/Subscription');
const Membership = require('../lib/Models/Membership');
const Period = require('../lib/Models/Period');
const EndedSubscription = require('../lib/Models/EndedSubscription');
const Errors = require('../lib/Models/Errors');
const CreateUserRequest = require('../lib/Models/CreateUserRequest');
const Errors2 = require('../lib/Models/Errors2');
const M200CreateUser = require('../lib/Models/M200CreateUser');
const AssignCoursesToUserRequest = require('../lib/Models/AssignCoursesToUserRequest');
const M200AssignCourseToUser = require('../lib/Models/M200AssignCourseToUser');
const UpdateUserRequest = require('../lib/Models/UpdateUserRequest');
const Errors4 = require('../lib/Models/Errors4');
const M200UpdateUser = require('../lib/Models/M200UpdateUser');
const M200DeleteUser = require('../lib/Models/M200DeleteUser');
const M200GetCourses = require('../lib/Models/M200GetCourses');
const Item1 = require('../lib/Models/Item1');
const Membership2 = require('../lib/Models/Membership2');
const M200PollActivityDatum = require('../lib/Models/M200PollActivityDatum');
const Lesson = require('../lib/Models/Lesson');
const User = require('../lib/Models/User');
const M403UserNotFoundException = require('../lib/Exceptions/M403UserNotFoundException');
const M403ValidationErrorException = require('../lib/Exceptions/M403ValidationErrorException');
const M500NonValidCourseIDException = require('../lib/Exceptions/M500NonValidCourseIDException');
const M403ValidationError2Exception = require('../lib/Exceptions/M403ValidationError2Exception');

const classMap = {
    M200GetUsers,
    Item,
    Course,
    Pagination,
    M200GetUser,
    FinishedLesson,
    InProgressLesson,
    PurchasedCourse,
    PurchasedLesson,
    Course1,
    ModulesAnalytic,
    LessonsAnalytic,
    Order,
    Course2,
    Checkout,
    Quize,
    Result,
    Reward,
    Subscription,
    Membership,
    Period,
    EndedSubscription,
    Errors,
    CreateUserRequest,
    Errors2,
    M200CreateUser,
    AssignCoursesToUserRequest,
    M200AssignCourseToUser,
    UpdateUserRequest,
    Errors4,
    M200UpdateUser,
    M200DeleteUser,
    M200GetCourses,
    Item1,
    Membership2,
    M200PollActivityDatum,
    Lesson,
    User,
    M403UserNotFoundException,
    M403ValidationErrorException,
    M500NonValidCourseIDException,
    M403ValidationError2Exception,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
